// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jagxrtojsnykiaomubyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImphZ3hydG9qc255a2lhb211Ynl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MjIzOTYsImV4cCI6MjA2ODM5ODM5Nn0.XkmhlKm0pk2XSyfYklGGfvQ5aWlgkd04ihzW4dC9PuY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});